all: 1 2

1:
	pandoc -f markdown+raw_tex -t pdf --metadata date="$(shell date +"%d/%m/%Y")" -o apartado-1.pdf apartado-1.md

2:
	pandoc -f markdown+raw_tex -t pdf --metadata date="$(shell date +"%d/%m/%Y")" -o apartado-2.pdf apartado-2.md
