#!/usr/bin/env python3

# import re
# import os
# import signal
import time
import subprocess
from pathlib import Path

def get_cpu_usage():
  with Path("/proc/stat").open("r") as f:
    # cpu [user] [nice] [system] [idle] [iowait] [irq] [softirq] [steal] [guest] [guest_nice]
    fields = list(map(int, f.readline().strip().split()[1:]))
    user, nice, system, idle, iowait, irq, softirq, steal, guest, guest_nice = fields
    idle_time = idle + iowait
    total_time = user + nice + system + idle_time + irq + softirq + steal + guest + guest_nice
    return total_time, idle_time

prev, prev_time = get_cpu_usage(), time.time()

load_cmd = ["sysbench", "--num-threads=6", "--test=cpu", "--cpu-max-prime=100000", "run"]
load = subprocess.Popen(load_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE) # noqa: S603

cpu = []
while load.poll() is None:
  time.sleep()
  current, current_time = get_cpu_usage(), time.time()
  total_diff, idle_diff = (a - b for a, b in zip(current, prev))
  cpu.append((1 - idle_diff / total_diff) * 100 if total_diff > 0 else 0)
  prev, prev_time = current, current_time

print(cpu)

# x1 = get_cpu_usage()
# time.sleep(1)
# x2 = get_cpu_usage()
#
# delta_total, delta_idle = (b-a for a, b in zip(x1, x2))
# print(x1, x2, delta_total, delta_idle, (delta_total-delta_idle)/delta_total * 100)






# monitor_cmd = ["bash", "-c", "top -b -d 1 | awk '/%Cpu\\(s\\):/ {print strftime(\"%Y-%m-%d %H:%M:%S\") \",\" 100-$8 \",\" $2 \",\" $4}'"]
# monitor = subprocess.Popen(monitor_cmd, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE) # noqa: S603

# command to simulate real command output
# load_cmd = ["bash", "-c", "cat sysbench.stdout.log && cat sysbench.stderr.log >&2 && sleep 2"]
# load_cmd = ["bash", "-c", "sysbench --num-threads=6 --test=cpu --cpu-max-prime=100000 run"]
# load = subprocess.run(load_cmd, capture_output=True, text=True, shell=False, check=False) # noqa: S603 # TODO: should check=True?
#
# os.killpg(monitor.pid, signal.SIGTERM)
# monitor.wait()
#
# print("################ STDOUT LOAD ################")
# print(load.stdout)
# print()
#
# print("################ STDERR LOAD ################")
# print(load.stderr)
# print("----------------------------------------")

# print("################ STDERR MONITOR ################")
# print(monitor.stderr.readline()) # type: ignore[union-attr]
# print("----------------------------------------")

# TIME_UNITS = { "h": 60*60, "m": 60, "s": 1, "ms": 1/1000, "us": 1/1000000 }
# ptrn = re.compile(r"^\s*(total time:)\s*\b(\d+\.\d+)(h|m|s|ms|us)\b")
# total_time = next(float(p.group(2)) * TIME_UNITS[p.group(3)] for l in load.stdout.splitlines() if (p := ptrn.search(l)))
# print(f"total time: {total_time}s")
# real, user, syst = map(float, load.stderr.splitlines()[0].strip().split(","))
# print(f"real: {real}s, user: {user}s, sys: {syst}s")
